#!/usr/bin/env bash

backup_help()
{
  printf "%b" "Backup your data with easy

Usage:

    sm backup [action]

Actions:

    setup [name] [-f]  #Generate basic backup script, use -f to overwrite existing file
    edit  [name]       #Edit backup script in your favorite editor
    examples           #show examples scripts for bdsm backup
"
}

backup_setup()
{
  local force=false token name target
  while array is nonempty extension_args
  do
    array shift extension_args token
    case $token in
      -f|--force)
        force=true
        ;;
      *)
        name=$token
        ;;
    esac
  done

  variables are nonempty name || error "please provide script name"

  target="$(
    files absolute path \
      $initial_pwd \
      $name
  )"

  if files exist $target
  then
    if $force
    then
      files remove $target
    else
      error "$name - backup script already exists"
    fi
  fi

  log_step "Generating backup script '${target}'"

  templates install $extension/backup.sh.template to $target

  templates seed $target \
    extension $extension

  files chmod 0755 $target

  log_step success
}

backup_examples()
{
  path enter "${extension_path}/examples"
  less -N *
}

backup_edit()
{
  target="$(
    files absolute path \
      $initial_pwd \
      $extension_args
  )"

  if files are missing $target
  then
    error "$extension_args - probably this is not a backup file"
  fi

  if command exists vim
  then
    DEFAULT=vim
  else
    DEFAULT=vi
  fi

  ${EDITOR:-$DEFAULT} $target
}
