#!/usr/bin/env bash

backup_help()
{
  description "Backup your data with easy"

  action "setup [name] [-f]" "Generate basic backup script, use -f to overwrite existing file"
  action "edit [name]" "Edit backup script in your favorite editor"
  action "examples" "show examples scripts for bdsm backup"
  #action "install [name]" "Add backup script to cron."
  #action "uninstall [name]" "Remove backup script from cron."
  #action "run [name]" "Run script"

  show_help usage
}

backup_setup()
{
  force=false
  while array_is_nonempty extension_args
  do
    array_shift extension_args token
    case $token in
      -f|--force)
        force=true
        ;;
      *)
        name=$token
        ;;
    esac
  done

  [[ -n "${name}" ]] || error "please provide script name"

  if [[ "${name:0:1}" == "/" ]]
  then
    target="$name"
  else
    target="$initial_pwd/$name"
  fi

  if $force
  then
    remove_files $target
  else
    if file_exists $target
    then
      error "$name - backup script already exists"
    fi
  fi

  install_template $extension/backup.sh.template to $target
  seed_template $target extension $extension
  ensure_files_are_executable $target
}

backup_examples()
{
  enter "${extension_path}/examples"
  less -N *
}

backup_edit()
{
  target="$initial_pwd/$extension_args"

  if file_is_missing $target
  then
    error "$extension_args - probably this is not a backup file"
  fi

  if command_exists vim
  then
    DEFAULT=vim
  else
    DEFAULT=vi
  fi

  ${EDITOR:-$DEFAULT} $target
}
