#!/usr/bin/env bash

target="$initial_pwd/$extension_args"

if file_is_missing $target
then
  error "$extension_args - probably this is not a backup file"
fi

if command_exists vim
then
  DEFAULT=vim
else
  DEFAULT=vi
fi

${EDITOR:-$DEFAULT} $target
