#!/usr/bin/env bash

force=false
while array_is_nonempty extension_args
do
  array_shift extension_args token
  case $token in
    -f|--force)
      force=true
      ;;
    *)
      name=$token
      ;;
  esac
done

variables_must_be_nonempty name
target="$(pwd)/$name"

if $force
then
  remove_files $target
else
  if file_exists $target
  then
    error "$name - backup script already exists"
  fi
fi

install_template backup.sh.template to $target mode 755
